### ISSUE TITLE
How to convert the .pb file？

### ISSUE THREAD

**Issue by tcxia** [Thinklab-SJTU/R3Det_Tensorflow#22]

**Comment by zouxiaoshi** [comment]
actually, it is possible to convert the checkpoint into savedmodel format(as well as .pb frozen graph),
but it IMPOSSIBLE to restore it from a serialized model (.pb or savedmodel) because py_func will not be saved during serialization.
https://www.tensorflow.org/api_docs/python/tf/py_function
You could rewrite those py_funcs since tf team has no plans to fix this up recently.

**Comment by yangxue0827** [comment]
Mainly the anchor generation part

**Comment by yangxue0827** [comment]
https://github.com/yangxue0827/RotationDetection/blob/main/tools/r3det/exportPb.py
@zouxiaoshi @tcxia

**Comment by zouxiaoshi** [comment]
> https://github.com/yangxue0827/RotationDetection/blob/main/tools/r3det/exportPb.py
> @zouxiaoshi @tcxia

This can be deployed through tensorflow serving ?
