### ISSUE TITLE
Pre Trained Model?

### ISSUE THREAD

**Issue by PhenomenalOnee** [Thinklab-SJTU/R3Det_Tensorflow#61]
Really Nice Work.
I want to test it on my images, but i cannot find pre-trained model links for R3det++ or  R3det?
Can you please provide the google drive links for the models
Thanks

**Comment by yangxue0827** [comment]
you mean [trained model](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md)?
Due to code updates, I cannot guarantee that these old links will work. If you cannot use it, you may need to roll back to an earlier version (may be this [version](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/tree/d137e4fa6a24cf0ee93000c47580a1460bb968d4)).

**Comment by PhenomenalOnee** [comment]
@yangxue0827 the links in earlier version are also not working (Page Not Found)

**Comment by yangxue0827** [comment]
There are some models that I have deleted, and the rest you need to see the current version of [MODEL_ZOO](https://github.com/Thinklab-SJTU/R3Det_Tensorflow/blob/master/MODEL_ZOO.md) @PhenomenalOnee

**Comment by yangxue0827** [comment]
You may need to retrain yourself. Because the code has been modified and improved a lot, the previous weighted probabilities cannot be used. @sergiev
